---
name: Roundcube Webmail
version: dev
slug: roundcube
description: Roundcube IMAP webmail client, exposed through Home Assistant ingress
url: https://github.com/teh-hippo/addon-roundcube
init: false
arch:
  - aarch64
  - amd64
ingress: true
ingress_stream: true
panel_icon: mdi:email
panel_title: Webmail
panel_admin: false
stage: experimental
apparmor: false
map:
  - share:rw
options:
  imap_host: ""
  imap_port: 993
  smtp_host: ""
  smtp_port: 465
  log_level: info
  plugins: []
  catchall:
    enabled: false
    autologin: false
    autologin_user: ""
    autologin_password: ""
    identity_autocreate: true
schema:
  imap_host: str
  imap_port: port
  smtp_host: str
  smtp_port: port
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
  plugins:
    - str
  catchall:
    enabled: bool?
    autologin: bool?
    autologin_user: str?
    autologin_password: password?
    identity_autocreate: bool?
