---
name: Roundcube Webmail
version: dev
slug: roundcube
description: Roundcube IMAP webmail client, exposed through Home Assistant ingress
url: https://github.com/teh-hippo/addon-roundcube
init: false
arch:
  - aarch64
  - amd64
ingress: true
ingress_stream: true
panel_icon: mdi:email
panel_title: Webmail
panel_admin: false
stage: experimental
apparmor: false
options:
  imap_host: ""
  smtp_host: ""
  log_level: info
  plugins: []
schema:
  imap_host: str
  smtp_host: str
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
  plugins:
    - str
