---
name: Roundcube Catch-all
version: dev
slug: roundcube-catchall
description: Identity auto-create on reply and optional autologin for catch-all Roundcube setups
url: https://github.com/teh-hippo/addon-roundcube
init: false
arch:
  - aarch64
  - amd64
stage: experimental
apparmor: false
map:
  - share:rw
options:
  identity_autocreate: true
  autologin: false
  autologin_user: ""
  autologin_password: ""
  log_level: info
schema:
  identity_autocreate: bool?
  autologin: bool?
  autologin_user: match(^$|^[^@\s]+@(?!-)[A-Za-z0-9-]{1,63}(?<!-)(\.(?!-)[A-Za-z0-9-]{1,63}(?<!-))+$)?
  autologin_password: password?
  log_level: "list(trace|debug|info|notice|warning|error|fatal)"
